#Metrics/LineLength:
#  Max: 1000
#
Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - lib/rails/generators/rails/gauranga_controller/templates/controller.rb
